version: '3.8'

services:
  razor_ef:
    image: razoref
    build:
      context: .
      dockerfile: Dockerfile
      target: final  # или base для VS отладки
    ports:
      - "8080:8080"  # HTTP
      - "8081:8081"  # HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ASP_Docker.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MySecurePassword123
    restart: unless-stopped