@host = https://localhost:7151
@api = {{host}}/api/orders
# <-- JWT из браузера
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hbmFnZXIiLCJyb2xlIjoiTWFuYWdlciIsIlVzZXJJZCI6IjIiLCJuYmYiOjE3NzIwMzY3MjMsImV4cCI6MTc3MjA0MDMyMywiaWF0IjoxNzcyMDM2NzIzfQ.xozDpBjI8sqpLxUH3C3KHf_0VJgX_CClFiAfJQcnPqI

### 🔥 1. Получить JWT токен (Admin)
# Разумеется никогда так не ставьте пароль если он не тестовый
POST {{api}}/jwt
Content-Type: application/json

{
  "UserName": "manager",
  "Password": "12345"
}

###
# Скопируйте token из JSON ответа → вставьте в @token выше 
# (Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...)

### Получить все заказы (Manager/Admin)
GET {{api}}
Accept: application/json
Authorization: {{token}}

### Получить заказ по ID (Manager/Admin)
GET {{api}}/14
Accept: application/json
Authorization: {{token}}

### Создать заказ (User/Manager/Admin)
POST {{api}}
Content-Type: application/json
Authorization: {{token}}

{
  "date": "2025-10-29T12:00:00Z",
  "clientId": 1,
  "productId": 1,
  "quantity": 2
}

### Обновить заказ (User/Manager/Admin)
PUT {{api}}/1
Content-Type: application/json
Authorization: {{token}}

{
  "date": "2025-10-30T10:00:00Z",
  "clientId": 1,
  "productId": 2,
  "quantity": 5
}

### Удалить заказ (Admin)
DELETE {{api}}/15
Authorization: {{token}}
